site_name: DevOps Package

theme:
  name: material
  features:
    - navigation.instant
    - navigation.instant.prefetch
    
nav:
  - Introduction: 'index.md'
  - Project Management:
    - 'Section 1': 'DevOpsPackageIntro.md'
  - Version Control:
    - 'Section 1': 'DevOpsPackageIntro.md'
  - Testing:
    - 'Section 1': 'DevOpsPackageIntro.md'
  - Automation and Build Server:
    - 'First section': 'AutomationBuildServer.md'

header_pages:
 - DevOpsPackageIntro.md
 - AutomationAndBuildServer.md
